services:
  bot:
    # Dockerfileがある場所を指定してビルドする
    build: .
    # 起動に失敗したら自動で再起動する
    restart: always
    # .envファイルから環境変数を読み込む
    env_file:
      - .env
    # データベースファイルの永続化
    volumes:
      - ./data:/app/data
    # データベースファイルを data ディレクトリに保存するための環境変数
    environment:
      - DATABASE_PATH=/app/data/study_data.db
